local mod = RegisterMod("Lazy Delver", 1)
local room = require("lazy_delver.room")
local render = require("lazy_delver.render")

mod:AddCallback(ModCallbacks.MC_POST_NEW_ROOM, function()
    room.obstacle_check()
    render.refresh()
end)
mod:AddCallback(ModCallbacks.MC_POST_UPDATE, function()
    render.tab_hold_check()
end)
mod:AddCallback(ModCallbacks.MC_POST_RENDER, function()
    render.render()
end)
mod:AddCallback(ModCallbacks.MC_POST_EFFECT_INIT, function(_, effect)
    room.bomb_check(effect)
end, EffectVariant.BOMB_EXPLOSION)
